// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package ma.Game.grpc;

public interface GuessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 winner = 2;</code>
   * @return The winner.
   */
  int getWinner();
}
