# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class GuessNumberGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GuessNumber = channel.stream_stream(
                '/GuessNumberGame/GuessNumber',
                request_serializer=game__pb2.GuessRequest.SerializeToString,
                response_deserializer=game__pb2.GuessResponse.FromString,
                )


class GuessNumberGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GuessNumber(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuessNumberGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GuessNumber': grpc.stream_stream_rpc_method_handler(
                    servicer.GuessNumber,
                    request_deserializer=game__pb2.GuessRequest.FromString,
                    response_serializer=game__pb2.GuessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GuessNumberGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GuessNumberGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GuessNumber(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/GuessNumberGame/GuessNumber',
            game__pb2.GuessRequest.SerializeToString,
            game__pb2.GuessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
