# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"\x1e\n\x0cGuessRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"0\n\rGuessResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06winner\x18\x02 \x01(\x05\x32\x45\n\x0fGuessNumberGame\x12\x32\n\x0bGuessNumber\x12\r.GuessRequest\x1a\x0e.GuessResponse\"\x00(\x01\x30\x01\x42\x10\n\x0cma.Game.grpcP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014ma.Game.grpcP\001'
  _GUESSREQUEST._serialized_start=14
  _GUESSREQUEST._serialized_end=44
  _GUESSRESPONSE._serialized_start=46
  _GUESSRESPONSE._serialized_end=94
  _GUESSNUMBERGAME._serialized_start=96
  _GUESSNUMBERGAME._serialized_end=165
# @@protoc_insertion_point(module_scope)
