// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package ma.Game.grpc;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GuessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GuessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\"\036\n\014GuessRequest\022\016\n\006number\030\001" +
      " \001(\005\"0\n\rGuessResponse\022\017\n\007message\030\001 \001(\t\022\016" +
      "\n\006winner\030\002 \001(\0052E\n\017GuessNumberGame\0222\n\013Gue" +
      "ssNumber\022\r.GuessRequest\032\016.GuessResponse\"" +
      "\000(\0010\001B\020\n\014ma.Game.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GuessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GuessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GuessRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_GuessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GuessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GuessResponse_descriptor,
        new java.lang.String[] { "Message", "Winner", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
