// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package ma.Game.grpc;

public interface GuessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
